### ISSUE TITLE
Add selection indices as an output of select_peaks

### ISSUE THREAD

**Issue by pauladkisson** [SpikeInterface/spikeinterface#1283]
Currently `sortingcomponents.peak_selection.select_peaks(input_peaks, ...)` outputs a structured numpy array `peaks` which is a 'smart' subset of the original `input_peaks` object. 

Frequently, we have to perform some costly operations, such as monopolar triangulation, on the originally detected `input_peaks` since we need peak locations for some of the peak selection algorithms.  But we may also need the results of these operations for each of the selected peaks, since for example, we need peak locations for some of the clustering algorithms.  To achieve common use-case, we would currently either have to
A) Recompute the peak locations of the selected peaks, which is costly for a large number of selected peaks
B) Determine the index of each selected peak in the original `input_peaks` object, which is also costly for large numbers of selected peaks and/or input peaks

To minimize unnecessary computation, I propose changing the output of `sortingcomponents.peak_selection.select_peaks` to include the selected indices so users can easily index prior computations.  Ex.
```
peaks = detect_peaks(...)
peak_locations = localize_peaks(peaks, ...)
selected_peaks, selected_indices = select_peaks(peaks, peak_locations, ...)
selected_locations = peak_locations[selected_indices]

assert selected_locations == localize_peaks(selected_peaks, ...)
```

Finally, I want to point out that one could imagine many different operations that could be useful for peak selection AND subsequent clustering (ex. what if you want to sample fast-spiking and regular-spiking neurons evenly, so you compute peak width).  So this improvement would be more general than this specific use case.

**Comment by yger** [comment]
In fact, the idea is clearly to use select_peaks() if possible before the localizations step, because some methods (like monopolar triangulation) will not scale properly for large number of peaks. In a nutshell, you detect all peaks, you consider only a subset (uniformly taken or with some "smart"/heuristic manner based on their amplitudes), and then, once you have this subset, you can get positions and feed that to motion correction algorithms.

That being said, I agree that maybe we could optionally return the indices of the selected peaks, in case people want to do funky operations afterwards on these particular peaks/time steps. As you are suggesting, we can even have selection methods that will depend on positions and/or properties of the peaks
