### ISSUE TITLE
Spikinterface has no attributes

### ISSUE THREAD

**Issue by McDr** [SpikeInterface/spikeinterface#14]
I first tried to run spiketoolkit without the spikeinterface meta package, just installed separately. I tried to run the command 
`import spiketoolkit as st`
`st.sorters.available_sorters()`

and got the error 

> AttributeError: module 'spiketoolkit' has no attribute 'sorters'

I found an open issue in spiketoolkit that suggested I try running spikeinterface instead as it is now packaged this way.  [](https://github.com/SpikeInterface/spiketoolkit/issues/209) 

I tried this and got the same thing: 
```
import spikeinterface as si 
si.sorters.available_sorters()
```

> AttributeError: module 'spikeinterface' has no attribute 'sorters'

It also seems that spikeinterface has no attributes that work (sorters, extractors, etc.). However, when I try it in Spyder IDE, it suggests all of them. 
<img width="194" alt="SI_attributeerror" src="https://user-images.githubusercontent.com/27747675/64132184-3228c300-cdce-11e9-8545-c50f0dafac14.png">

**Comment by samuelgarcia** [comment]
For the first part.
For cycle import reason sorters is now totally out of spiketoolkit.
So you need to do ```import spikesorters as ss``` and ```ss.available_sorters()```

For ```AttributeError: module 'spikeinterface' has no attribute 'sorters' ```, this is strange.
Because, I have the same bug when I do it in ipython/jupyter but not in a script.

@alejoe91 : do you experience the same ?

See here https://github.com/SpikeInterface/spikeinterface/pull/13, there is a test_import that is OK with travis and my machine. But the same in ipython do not work.
We could fix this by importing everything in the init but the import would be slower.
with:
```python
from . import extractors
from . import sorters
...
```
what do you htink ?

**Comment by alejoe91** [comment]
@McDr can you try:

```
import spikeinterface.sorters as ss
ss.available_sorters()
```

This works for me.

@samuelgarcia this is strange. If I do:

```
import spikeiterface.sorters as ss
ss.available_sorters()
```

it works. If I only import `spikeinterface` all I can access is `version`...

**Comment by samuelgarcia** [comment]
SAme for me in ipython but not in a script this the test I made on the PR.

**Comment by alejoe91** [comment]
@samuelgarcia what you suggest works. Let's do that

**Comment by samuelgarcia** [comment]
Yes but it make the metapackage enormous!!!!
Like if scipy would import everything at the beginning but not on demand.
I am not very happy with this solution.

**Comment by alejoe91** [comment]
what about lazy imports?

**Comment by samuelgarcia** [comment]
It was a lazy import but this bug sometimes.

The ```from . import sorters``` is a full import.

**Comment by alejoe91** [comment]
I'll make a PR to show you what I mean :)

**Comment by alejoe91** [comment]
Ok I was kidding. What I had in mind doesn't work. Let's just use this:

```
from . import extractors
from . import toolkit
from . import sorters
from . import comparison
from . import widgets
```

It's not so huge. Alternatively, we can 'force' the user to import separate modules when needed:

```
import spikeinterface.extractors as se
```

**Comment by McD-NMI** [comment]
@alejoe91 What you suggested: 

`importspikeinter.spikesorters as ss` 
`ss.available_sorters() `

works for me as script or in IPython.

**Comment by alejoe91** [comment]
Hi @McD-NMI and @McDr 

With the latest commit, also:

```
import spikeinterface as si
si.sorters.available_sorters()
```

should work. Can you confirm that?

**Comment by McD-NMI** [comment]
@alejoe91 

I can confirm this works now!

**Comment by yilmazduygu** [comment]
Hi! 
I've been trying to get my recordings sorted using one of the tutorial notebooks. Unfortunately I can't retrieve the waveforms, because I get the error `AttributeError: module 'spikeinterface' has no attribute 'WaveformExtractor'`
I'm also getting this output when I try `si.version`:
`<module 'spikeinterface.version' from '/opt/anaconda3/envs/spiketutorial/lib/python3.6/site-packages/spikeinterface/version.py'>`, which I thought was strange.

Attaching this, in case it's helpful:
[pip_list.txt](https://github.com/SpikeInterface/spikeinterface/files/7190460/pip_list.txt)

-duygu

**Comment by alejoe91** [comment]
Hi @yilmazduygu 

The new version (>=0.90) doesn't use the packages `spikeextractors`, `spiketoolkit`, `spikesorters`, `spikecomparison`, and `spikewidgets`. So you can uninstall them. To access the version you can do `si.__version__`.

Can you share your entire script/notebook? Which tutorial are you running? Indeed it'strange that the `WaveformExtractor` is not found...

Cheers
Alessio
