### ISSUE TITLE
Question about Hungarian & Best Match: how to decide the score?

### ISSUE THREAD

**Issue by ZoeChen96** [SpikeInterface/spikeinterface#1639]
Hello,

I want to make a performance comparison among different sorters. From the [document](https://spikeinterface.readthedocs.io/en/latest/modules/comparison.html#more-information-about-hungarian-or-best-match-methods), I see that there are 2 types of match mode. To my understanding, **Hungarian** will give a one-to-one mapping; while **Best-Match** will always keep the best match, so multiple match is allowed.

However, I wonder how you choose the 'score' for them. I see the default score for Hungarian is `match_score=0.5`; while for Best Match is `chance_score= 0.1`. I have a small test (for example Hungarian) , and I found the units with score < match_score is clamped to 0. Why would you use that settings? And why did you choose 0.5 and 0.1 seperately for Hungarian and Best Match comparing?

PS: You mentioned that in spikeforest you are using Best match. How much is the score in that case? Is that 0.1? How shall I find it?

Sorry for the disturbing, thank you in advance!

**Comment by ZoeChen96** [comment]
By the way, some papers define the accuracy just on acc = TP/(TP+FP+FN), but not on the basis of the units (or neurons in your cases). Can spikeinterface evaluate the sorters in this traditional way?

**Comment by samuelgarcia** [comment]
OK I get what you mean.
In my mind pool_with_average is the average acrros units of the accuracy. I think this is the correct way.
You summary to a unit number.

The other formula you propose that come from "old paper" is (from what I understand) a pooling of all spike of all units. And then compute accuracy.
I would not use this because, units with lot of spikes ( high firing rate) will dominate the results.
I do not think we ever use this in spikeinterface, maybe I am wrong.

What I would recommand is another way : you should count units in some range of accuracy, for instance
  * 95-100 : very good units
  * 85-95 : good units
  * 50-85 : detected but low quality
  * 10 - 50 : low match
  * 0 - 10 not matched units

And so you summary you performances with a unit count by quality of match.
It is more or less what we need more or less in this [paper](https://elifesciences.org/articles/61834) figure 2C.
you have this kind of machinery inside spikeinterface but it is easy to adapt with other threhold.
