### ISSUE TITLE
Probe evaluation, make the sorting faster.

### ISSUE THREAD

**Issue by YinJiapeng** [SpikeInterface/spikeinterface#1914]
I am sorting data collected from the MEA. I want to make a evaluation of the performance of the electrode.

I want to know if a channel of the MEA works. So I want to get the activity data from each channel, neglecting cross channel activity.

When I set detect_channel_radius = 1, adjacency for detect spikes with channel radius is 1, I found the sorting speed is still quite slow. 

The result in sparsity.json is :

{"unit_id_to_channel_ids": {"1": ["0", "1"], "2": ["0", "1", "2"], "3": ["1", "2", "3"], "4": ["3", "4", "5"], "5": ["4", "5", "6"], "6": ["6", "7", "8"]}, "channel_ids": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"], "unit_ids": [1, 2, 3, 4, 5, 6]}

It seems the calculation is performed not in 1 channel by 1 channel way. Why the sorted result is still 2-3 channels together?

How to make the sorting in a more efficient way for probe evaluation?

Thanks.

**Comment by alejoe91** [comment]
Hi @YinJiapeng 

I recommend using peak detection, instead of spike sorting, for this purpose. See the [detect_peaks](https://spikeinterface.readthedocs.io/en/latest/api.html#module-spikeinterface.sortingcomponents.peak_detection) function.

The `by_channel` method, will treat each channel as independent:

```
from spikeinterface.sortingcomponents.peak_detection import detect_peaks 

peaks = detect_peaks(recording, method="by_channel")
```

The `peaks` will contain the `channel_index` of each detected peaks. You can count the number of peaks detected on each channel with a simple `np.unique`:

```
active_channel_idxs, num_peaks_per_channel = np.unique(peaks["channel_index"], return_counts=True)
```

Hope this helps!
