### ISSUE TITLE
Saved Sorter Object has no information about the mapping from units to channels

### ISSUE THREAD

**Issue by Sudhanshu-Sb2002** [SpikeInterface/spikeinterface#1952]
The entire spikesorter output (the .npz file and other files exported) doesn't have any information about which electrode/channels the unit belongs to. What is the use of unit-ids if I don't know which channels they came from?

**Comment by alejoe91** [comment]
Unit ids are the IDs that a sorter assigns to each unit. Toe `Sorting` ibject itself doesn't know the channels a unit was found on, even because many times it's multiple channels.

To combine the information of a spike sorter output with the recording you should `exrtact_waveforms` and use the `WaveformExtractor`.

See here: https://spikeinterface.readthedocs.io/en/latest/modules/core.html#waveformextractor
