### ISSUE TITLE
Unify notation in ISI violations docs

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeinterface#2050]
While the page on ISI violations is super useful, we should unify the notations between differen methods to improve readibility:

https://spikeinterface.readthedocs.io/en/latest/modules/qualitymetrics/isi_violations.html

**Comment by zm711** [comment]
Is this linked to #1973. Or a completely separate desire for a rewrite to clarify?

**Comment by chrishalcrow** [comment]
Hello,

Thought I'd take a look at this, and found something fun(?). In their paper, Hill et. al. state that "The expected number of refractory period violations, $r$, is given by the total duration of refractory periods around true spikes multiplied by the rate of rogue spikes, or $r = 2 (\tau_R − \tau_C) N^2(1 − f_1^p)f_1^p/T$, which can be solved for $f_1^p$." The quantity $f_1^p$ is the contamination. Let's solve the quadratic for $f_1^p$:
$$f_1^p = \frac{1}{2}\left(1 - \sqrt{1 - \frac{2rT}{N^2(\tau_R − \tau_C)} }\right)$$
which is (basically) the second equation from the Llobet method.

I can't figure out where the Hill equation that we use comes from. If you assume that $\frac{2rT}{N^2(\tau_R − \tau_C)}$ is small, you get by Taylor Series:
$$f_1^p \approx \frac{1}{2}\left(1 - \left(1 - \frac{rT}{N^2(\tau_R − \tau_C)}  \right)\right) =\frac{rT}{2N^2(\tau_R − \tau_C)} $$
which is the Hill result.

Regardless, I'll have a go at unifying the notations!

**Comment by zm711** [comment]
Hey Chris, check out the link at #1973 as well. Basically, our implementation was from a Matlab repo called `sortingQuality` done by Nick Steinmetz. He actually changed  his implementation last year because of the way the LLobet paper solved the math stuff. So this is a bit of mess at the moment in my opinion which is why I never braved trying to do this, but our implementation is based on his original solution around the Hill paper while trying to eliminate complex solutions.

(nice equation rendering. I always mess latex type stuff up and have to redo a million times).

**Comment by chrishalcrow** [comment]
Ahhh, I see. In an ideal world, I think we should get rid of our "Hill implementation" because 1) it's not the Hill implementation 2) the result isn't published anywhere; and is especially obscure now that Nick has changed his code.

So I'd vote to deprecate `isi_violation`, advising that `rp_violation` will give similar values for units that aren't _very_ contaminated. But now things like the automated curation ML mode uses this metric, so deprecating isn't without harm... 

It seems like this kinda thing could be a problem in the future: there can easily be new quality metrics, or improvements/corrections to them.

(I got two things from my maths degree: Taylor Series and latex typing)

**Comment by chrishalcrow** [comment]
Oh wait, this metric is published in UltraMegaSort here: https://github.com/danamics/UMS2K/blob/master/quality_measures/rpv_contamination.m
So, at least for now, we should cite this instead of the original Hill paper. Working on it now...
