### ISSUE TITLE
For Kilosort4, `export_to_phy()` creates `params.py` with `dtype = 'float32'` instead of `dtype = 'int16'`

### ISSUE THREAD

**Issue by louiskang** [SpikeInterface/spikeinterface#2738]
(Hope this issue is more universal than the last one.) I've had problems with running `phy extract-waveforms params.py` with outputs from SpikeInterface and Kilosort4. Phy would return a `Could not load spike waveforms: mmap length is greater than file size.` error and the extracted waveforms could not be loaded. I did not have this problem with SpikeInterface and Kilosort3.

It appears that for Kilosort4, SpikeInterface prints `dtype = 'float32'` in `params.py`, but for Kilosort3 and Kilosort2.5, it prints `dtype = 'int16'`. Also it appears that Kilosort of any version expects by default `int16`-formatted binary files according to their latest Nature Methods paper. By changing this line back to `dtype = 'int16'`, phy waveform extraction and subsequent visualization seems to work fine. So the most parsimonious explanation to me is that SpikeInterface makes an error in printing Kilosort4 `params.py`, but please let me know if the binary data are indeed changed to `float32` for Kilosort4--I can then investigate more on my end where an inconsistency might be introduced in my analysis pipeline.

Thanks!

**Comment by alejoe91** [comment]
Hi @louiskang 

Kilosort4 provides a direct wrapper to SpikeInterface objects that it's used by SpikeInterface. This means that KS4 can also work with float data, while only Phy requires int16. So the `float` in the `params.py` is actually correct and you should not change it to `int16`, otherwise the data loading might be wrong.

Note that you can force a dtype before running Kilosort in SpikeInterface:
```
rec_int16 = spre.astype(rec_float, "int16")
```
