### ISSUE TITLE
Scale setting for sorting analyzer extension

### ISSUE THREAD

**Issue by Hobart10** [SpikeInterface/spikeinterface#2751]
Hi, thank you for developing and maintaining this wonderful module and community! 
I had several issues in computing extension `spike_amplitudes` and exporting to phy with the extension.
Phy exporting requires sorting analyzer parameter `return_scaled` to be False, but seems the default parameter for `spike_amplitudes` computation is True and there are no option to modify. And if I don't specify the dtype of `waveforms` extension to 'int16', the scaling error will happen there. 
Spikeinterface version: lastest; kilosort 4 version: 4.0.4.
Any help of how I can export will be highly appreciated! 

Error info:
`ValueError: get_dense_templates_array: return_scaled=True is not possible SortingAnalyzer has the reverse`

Code snippet:
```
    sorting_KS4 = si.run_sorter(sorter_name='kilosort4', recording=rec_saved, 
                                output_folder=Path(folder_out) / 'results_KS4', remove_existing_folder=True,
                                verbose=False, **ks4_params_modSet_NX)

    folder_analyzer = Path(folder_out) / "sortingAnalyzer_KS4";
    sorting_analyzer = si.create_sorting_analyzer(sorting=sorting_KS4, recording=rec_saved, 
                                          folder=folder_analyzer, format="binary_folder", sparse=False, 
                                          return_scaled=False, overwrite=True, **global_job_kwargs)
    sorting_analyzer.compute("random_spikes")
    sorting_analyzer.compute("waveforms", dtype='int16')
    sorting_analyzer.compute("templates", operators=["average", "median", "std"])
    sorting_analyzer.compute("spike_amplitudes", peak_sign="both")
    sorting_analyzer.compute("template_similarity")

    si.export_to_phy(sorting_analyzer, output_folder=folder_out / 'phyOut_KS4', 
                 compute_pc_features=True, compute_amplitudes=True, 
                 copy_binary=False, remove_if_exists=True, peak_sign = "both", **global_job_kwargs)
```

**Comment by zm711** [comment]
@Hobart10,

You're right. We recently switched to return_scaled as a variable at the sorting_analyzer level. We missed switching over the init here

https://github.com/SpikeInterface/spikeinterface/blob/163ab282645e62fbfd75cd845eb7755da187c787/src/spikeinterface/postprocessing/spike_amplitudes.py#L146-L157

We will fix it!

**Comment by zm711** [comment]
Actually I think I tracked down the real issue. It is that we use the default return_scaled=True here

https://github.com/SpikeInterface/spikeinterface/blob/163ab282645e62fbfd75cd845eb7755da187c787/src/spikeinterface/core/template_tools.py#L56-L61


Because here we don't give the explicit return_scaled.

https://github.com/SpikeInterface/spikeinterface/blob/163ab282645e62fbfd75cd845eb7755da187c787/src/spikeinterface/core/template_tools.py#L150

I will submit a PR in little bit :)

**Comment by zm711** [comment]
@alejoe91 @samuelgarcia 

So we need to be able to use return_scaled in  `get_template_amplitudes` but the function needs to accept `SortingAnalyzer` or `Templates`, but `Templates` doesn't have a global `return_scaled` like `SortingAnalyzer`. How do we want to deal with this?

**Comment by alejoe91** [comment]
Maybe just ignore the return_scaled if a Templates object is passed?

**Comment by zm711** [comment]
So in the PR I just sent `return_scaled` to True (the previous behavior) if a `Templates` object is passed since it is a required argument for the function. Let me know if you want something else.

@Hobart10, if you want to test this for us you can install from the linked PR and see if that fixes your issue. We might be missing another spot so it would be cool to have someone test this so we can make sure all steps are working :)

**Comment by zm711** [comment]
Good catch @Hobart10 ! I just patched that and found one other spot in template tools where we needed to grab the `return_scaled`. Could you try now with the same PR!

**Comment by zm711** [comment]
@Hobart10 We'll close this one when the PR is merged :)
