### ISSUE TITLE
Numpy version within docker container

### ISSUE THREAD

**Issue by OlivierPeron** [SpikeInterface/spikeinterface#3192]
Hello, 

I am using the sorters through dockers, and especially **Kilosort 2.5**, but since **numpy 2** has been released, all my sorting attempts failed. When installing numpy in the container, no version is specified, therefore the latest version is installed, which is not supported by spikeinterface. 
For example, I encountered the following error within the container:

AttributeError: `np.issctype` was removed in the NumPy 2.0 release. Use `issubclass(rep, np.generic)` instead.

Thanks !

**Comment by zm711** [comment]
Which version of spikeinterface are you using. I think we have this fixed as of 0.100.8, the 0.101.0rc0, and in main.

**Comment by OlivierPeron** [comment]
I am using version 0.101.0rc0 ! I can try to upgrade to new versions !

**Comment by zm711** [comment]
You have two options. If you are set on your current version then you can try

```python
run_sorter(..., extra_requirements="numpy==1.26", docker_image=True, ...)
```

Otherwise this should be fixed in 0.101.0 on main (not the release candidate). The release of 0.101.0 on pypi will be soon, but if you want to work on stuff today I would just install from source or force the requirement in the run_sorter function.

**Comment by OlivierPeron** [comment]
Ok I will try this ! Looks like the easier way indeed ! Thanks !

**Comment by OlivierPeron** [comment]
It worked just fine using your recommendation ! Thanks, I am closing the issue !
