### ISSUE TITLE
Good setups for low density arrays

### ISSUE THREAD

**Issue by skeltoh** [SpikeInterface/spikeinterface#498]
I'm trying to setup a pipeline to spikesort recordings using 16 channels, 150um spacing arrays, with minimal subjective curation.  Does anyone have any good starting points for setups that have worked with similar recordings, including the spike sorting software and settings? It seems like most of what I've tried (spyking circus, kilosort2) is making assumptions based on denser arrays, and giving me an unrealistic number of units that have not been merged aggressively enough.

**Comment by samuelgarcia** [comment]
Did you try tridesclous ?
tridesclous is quite a big conservative for total unit number.
Note that tridesclous is a bit complicated to install due to numpy version constrain. See [this](https://github.com/SpikeInterface/spikeinterface/tree/master/installation_tips)

Also not that you should also try the spikeinterface-gui. This is a good help to understand why some sorter given a parameters set give strange results.


Dislamer : I am the author of tridesclous.
