### ISSUE TITLE
Reading Intan RHD files

### ISSUE THREAD

**Issue by benkiisma** [SpikeInterface/spikeinterface#576]
Hello, 

I have an issue with the reading of my files on SpikeInterface following the 
I am trying to read Intan (.rhd) files with the following function : _**spikeextractors.extractors.intanrecordingextractor.intanrecordingextractor.IntanRecordingExtractor()**_.
With that function, I managed to read the file, do the preprocessing, the caching and the dumping of the recording. I start having issues at the spikesorting level: Klusta and TridesclousSorter works well whereas all the others fail to run outputing the error : **_Spike sorting failed: returned a non-zero exit code._** 
I am wondering if there is a way ( SpikeInterface function or others) that could convert my Intan file to a binary file (.bin) that would allow me to use different sorters and do the spike sorting comparison.

Thank you.

**Comment by alejoe91** [comment]
Hi @benkiisma 

The spike sorting failure is not due to the file format of the data. Once the file has been *extracted* and loaded in SpikeInterface, the spike sorters "don't know" where the file came from. Sometimes spike sorters just fail, for example if not enough spikes are found etc.

We strongly recommend to switch to the new spikeinterface version. You can find a getting started tutorial [here](https://spikeinterface.readthedocs.io/en/latest/getting_started/plot_getting_started.html). To read RHD files in the new version you can simply do:

```
import spikeinterface.extractors as se

recording = se.read_intan('path-to-file.rhd')
```

Cheers
Alessio
