### ISSUE TITLE
get_unit_waveforms not taking params

### ISSUE THREAD

**Issue by guitchounts** [SpikeInterface/spikeinterface#73]
I'm trying to get waveforms from a sorting and need 1) only one channel instead of all channels, 2) +/- 1 ms instead of +/-3, and 3) more spikes than the default 1000. I'm trying two different ways of passing the params to `get_unit_waveforms` but the output is always the same (e.g. `waveforms[0].shape = (1000, 32, 180)` instead of e.g. `(10000,1,60)`. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/2030372/91187693-720f4700-e6be-11ea-9322-767b1fcf7252.png)

**Comment by alejoe91** [comment]
Hi @guitchounts 

Since the first time you saved the waveforms as features (`save_as_features=True`), the next times you call the `get_unit_waveforms` it will return the already computed once. To recompute, you can use the `recompute_info=True` param (note that this holds for all `postprocessing`, `validation`, and `curation` functions)
