### ISSUE TITLE
`has_scaled_traces()` method renamed to `has_scaled`

### ISSUE THREAD

**Issue by h-mayorquin** [SpikeInterface/spikeinterface#858]
I don't know if it was intended but one the commits in the last two days (Today being 2022-01-01) changed the name of `has_scaled_traces` to `has_scaled` in the master branch and broke our stuff in neuroconv:

https://github.com/catalystneuro/neuroconv/pull/45

I think is this new re-organization around the concept of snippets. This is the new function which also seems repeated and with a new name:
https://github.com/SpikeInterface/spikeinterface/blob/678a31eca474027e7d8497e4f2bc7c8746bb2ee1/spikeinterface/core/baserecordingsnippets.py#L49-L64

Maybe I am getting something wrong.

**Comment by alejoe91** [comment]
Hi @h-mayorquin 

I though I left the `has_scaled_traces()` for back compatibility, but I'll double check! In case it's not there we'll re-add it. 

The rationale is that since now the BaseSnippets and BaseRecording inherit from the same class, the semantic of `has_scaled_traces()` only applies to the Recording, while `has_scaled()` is more general. Let's discuss about it tomorrow

**Comment by h-mayorquin** [comment]
Yes, I think you accidentally removed it from `BaseRecording`.
