### ISSUE TITLE
Stability of the API

### ISSUE THREAD

**Issue by teristam** [SpikeInterface/spikeinterface#883]
Hi,

First, thank you so much for developing this amazing spike sorting package. I have been using it in our data pipeline. However, I notice that the API often undergo big breaking changes every once in a while and all our existing code breaks whenever we try to update the package. Does spikeinterface have any plan to freeze the external API? It is good to keep improving the package but if the API keeps breaking at such a fast pace it is very difficult to maintain a reliable data pipeline that depends on it. 

Thank you for your time and attention!

**Comment by samuelgarcia** [comment]
Hi,
we had a big big API breaking last year 0.13.0 to 0.90.0.
It was really was necessary to fix some error design in the spikeinterface infancy.
Despite this big API changing the felling is the same as before.

Since 0.90.0, normally we have very few "API change".
In short we try to, improve without breaking anything.
Sometimes we have some small changes that are easy to fix in pipeline.
I would say that core/extractor/sorter have almost no changes that could break pipeline. Maybe I am wrong.
postprocessing/preprocessing get lot of great changes across versions, so yes in theses you can except some ajustment everytimes you update spikeinterface.
sortingcomponent module is totally experimental so there you can have api change every weeks!!
