### ISSUE TITLE
Recording's channel ids lost when adding a probe

### ISSUE THREAD

**Issue by TomBugnon** [SpikeInterface/spikeinterface#886]
Hi,

When adding a probe with 
```
rec = rec.set_probe(prb)
```
the recording's channel ids are reverted to `[1, ..., nchans]`, even if the probe's contact ids are set beforehand with `prb.set_contact_ids(rec.get_channel_ids())`.

The doc is either unclear or absent on these points. What's the preferred way to add a probe and making sure not to mix up all the channels? What's the difference between contact id and channel id?

**Comment by samuelgarcia** [comment]
I not sure to understand.

The **channel_id** refer to name of the recording device (for instance openephys or blacbrock).
The **contact_id** refer to the name given by the probe manufacturer of the "channel" aka contact on the probe.

the role of `rec = rec.set_probe(prb)` is to link channel_id to contact_id which often complicated because of the wiring of the headstage. the probe have internaly a channel_device_index that help for this operation.
After this the **channel_id** is not changed for the recording BUT the internal probe of the recording have a re sorted version of the probe. In short contact are sorted to match there channel.

Did you look at this : https://probeinterface.readthedocs.io/en/main/examples/ex_11_automatic_wiring.html

You should not do this `prb.set_contact_ids(rec.get_channel_ids())`. contact_id should be kept and you should only play with the device channel index of the probe before doing the set_probe
