### ISSUE TITLE
Mountainsort problem: Cannot propagate registered recording to UnitsAggregationSorting

### ISSUE THREAD

**Issue by SusanL82** [SpikeInterface/spikeinterface#931]
Hello, 
I'm running into a problem with Mountainsort and I'm not sure how to solve it. 
I'm not sure how to attach files, so you can see the input files and my script here: https://owncloud.cesnet.cz/index.php/s/BjAj0CBHM2pCWtP

I load my files (Neuralynx CSC) using spikeinterface, add our own channel grouping, concatenate segments (if > 1) and then run mountainsort by group. Like so:  

sorting_MS = ss.run_sorter_by_property("mountainsort4",recording, grouping_property = "group", working_folder = this_working_folder, mode_if_folder_exists = 'overwrite', engine = 'loop', verbose = True, **default_MS)

The sorting seems to run ok, but it ends with the following warning: 
C:\Users\susan\anaconda3\envs\sort\lib\site-packages\spikeinterface\core\unitsaggregationsorting.py:71: UserWarning: Cannot propagate registered recording to UnitsAggregationSorting
  warnings.warn(

In a different issue, a suggested solution was to save the mountainsort outputs to a separate folder, but that doesn't seem to help. I think the issue may come from within the run_sorter_by_property() function. 

Any suggestions as to what I may be doing wrong?
Susan

[SI_sorting_pipeline.txt](https://github.com/SpikeInterface/spikeinterface/files/9506652/SI_sorting_pipeline.txt)

**Comment by alejoe91** [comment]
Hi @SusanL82 

Don't worry, that is just a warning but it is indeed a useless and criptic one, so I removed it here: https://github.com/SpikeInterface/spikeinterface/pull/937
It does not affect the results :)

Here is an explanation: when you use the `ss.run_sorter_by_property`, the original recording is split in different subrecordings that are spike sorted separately. When spike sorting is finished, the recording that was sorted is "registered" to the sorting object. When the output of the different sorting is combined (`UnitAggregationSorting`), the recording registered to each subsorting is not propagated, because now you have one `Sorting` object out of many. In the same PR I added a fix to attach the original full recording to the aggregated sorting output (see [here](https://github.com/alejoe91/spikeinterface/blob/aggregate_units/spikeinterface/sorters/launcher.py#L144)).
